name: Test castlabs integration

on: workflow_dispatch

jobs:
  test:
    name: Test castlabs integration (windows)
    runs-on: windows-latest
    timeout-minutes: 15

    env:
      CASTLABS_ACCOUNT_NAME: ${{secrets.CASTLABS_ACCOUNT_NAME}}
      CASTLABS_PASSWORD: ${{secrets.CASTLABS_PASSWORD}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Version
        run: python --version
        shell: sh
