name: notarytool history

on: workflow_dispatch

jobs:
  test:
    name: Test mac notarytool
    runs-on: macos-latest
    timeout-minutes: 90

    env:
      DEBUG: 'electron-notarize'
      APPLE_ID: ${{secrets.APPLE_ID}}
      APPLE_ID_PASSWORD: ${{secrets.APPLE_ID_PASSWORD}}
      APPLE_TEAM_ID: ${{secrets.APPLE_TEAM_ID}}
      CSC_LINK: ${{secrets.APPLE_CERT_BASE64}}
      CSC_KEY_PASSWORD: ${{secrets.APPLE_CERT_PASSWORD}}
      GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Update NPM
        run: |
          npm install -g npm@latest

      - name: Install dependencies
        run: |
          npm install --legacy-peer-deps

      - name: notarytool history
        run: xcrun notarytool history --apple-id ${{secrets.APPLE_ID}} --password ${{secrets.APPLE_ID_PASSWORD}} --team-id ${{secrets.APPLE_TEAM_ID}}

      - name: notarytool last invalid run
        run: xcrun notarytool log 59eda425-049f-48f0-ad42-0524b1cdc78f --apple-id ${{secrets.APPLE_ID}} --password ${{secrets.APPLE_ID_PASSWORD}} --team-id ${{secrets.APPLE_TEAM_ID}}

      - name: notarytool first inprogress run
        run: xcrun notarytool log 6d75594c-f8d3-445c-903c-9e18f40e7ae6 --apple-id ${{secrets.APPLE_ID}} --password ${{secrets.APPLE_ID_PASSWORD}} --team-id ${{secrets.APPLE_TEAM_ID}}
