name: Test castlabs integration

on: workflow_dispatch

jobs:
  test:
    name: Test castlabs integration (windows)
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Install castlabs-evs
        run: python -m pip install --upgrade castlabs-evs

      - name: Test castlabs-evs
        run: python -m castlabs_evs.account --version

      - name: Authorize
        run: python -m castlabs_evs.account reauth -A ${{secrets.CASTLABS_ACCOUNT_NAME}} -P ${{secrets.CASTLABS_PASSWORD}}
